add missing include for gcc15 (#75) (#78)
fix:
```cpp
In file included from /build/point_cloud_transport_plugins-release-release-humble-zlib_point_cloud_transport-1.0.13-1/src/zlib_cpp.cpp:29:
/build/point_cloud_transport_plugins-release-release-humble-zlib_point_cloud_transport-1.0.13-1/src/zlib_cpp.hpp:43:3: error: 'uint8_t' does not name a type
   43 |   uint8_t * ptr;
      |   ^~~~~~~
```

(cherry picked from commit d17fab0e48151510b5daba8fec84778f7cf3752f)

Co-authored-by: Guilhem Saurel <guilhem.saurel@laas.fr>