add missing include for gcc15
fix:
```cpp
In file included from /build/point_cloud_transport_plugins-release-release-humble-zlib_point_cloud_transport-1.0.13-1/src/zlib_cpp.cpp:29:
/build/point_cloud_transport_plugins-release-release-humble-zlib_point_cloud_transport-1.0.13-1/src/zlib_cpp.hpp:43:3: error: 'uint8_t' does not name a type
   43 |   uint8_t * ptr;
      |   ^~~~~~~
```